run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - .git
    - docs
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  gocognit:
    min-complexity: 30  # 临时放宽
  
  lll:
    line-length: 140  # 临时放宽
    
  funlen:
    lines: 120  # 临时放宽
    statements: 60

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # - godot  # Temporarily disabled due to issues with Chinese comments
    - gofmt
    - gofumpt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - unused
    - path: examples/
      linters:
        - unused
  exclude-dirs:
    - vendor
    - .git
    - docs
  exclude-files:
    - ".*_test.go"
