name: Gradle Parser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests and examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install dependencies
        run: go get -v ./...

      - name: Run unit tests
        run: go test -v ./...

      - name: Run basic example
        run: cd examples/01_basic && go run main.go

      - name: Run dependencies example
        run: cd examples/02_dependencies && go run main.go

      - name: Run plugins example
        run: cd examples/03_plugins && go run main.go

      - name: Run repositories example
        run: cd examples/04_repositories && go run main.go

      - name: Run complete example
        run: cd examples/05_complete && go run main.go 